import { ICategory } from "../../categories/interface/categories.interface";
import { ISeason } from "../../seasons/interface/season.interface";
import { ITeam } from "../../teams/interfaces/teams.interface";

// Generated by https://quicktype.io

export interface ILeaderboard {
    leaderboardId?: number;
    teamId:       number;
    seasonId:     number;
    categoryId:   number;
    points:       number;
    matchesWon:   number;
    matchesLost:  number;
    matchesDrawn: number;
    goalsScored:  number;
}

export interface ILeaderboardResponse {
    leaderboardId: number;
    teamId:       number;
    teamName:     string;
    seasonId:     number;
    seasonName:   string;
    categoryId:   number;
    categoryName: string;
    points:       number;
    matchesWon:   number;
    matchesLost:  number;
    matchesDrawn: number;
    goalsScored:  number;
}
